version: '2'
services:    
    apache-php:
        build: ./images/httpd_php        
        links:
            - mysql
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./www:/var/www
            - ./hosts:/etc/apache2/sites-enabled
            - ./logs:/var/log/apache2
    mysql:
        image: mariadb:latest
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: qwerty

